name = "svelte-worker"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "./workers-site/webpack.config.js"

[site]
bucket = "./public"
entry-point = "workers-site"
